// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs_h3Kw7EHqi6n_r63BhfO_yMrOCB0XVs',
    appId: '1:282053984724:web:5e7440778c4e4e35e99641',
    messagingSenderId: '282053984724',
    projectId: 'wa-apps-28f9a',
    authDomain: 'wa-apps-28f9a.firebaseapp.com',
    storageBucket: 'wa-apps-28f9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4X_Qk-ZhTxK3wezB364jBIY9Xh8bEGCo',
    appId: '1:282053984724:android:a59b2240c813b0e2e99641',
    messagingSenderId: '282053984724',
    projectId: 'wa-apps-28f9a',
    storageBucket: 'wa-apps-28f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJicLaUThPDnR0Kesa4W6_4TUw4Eqj1Ts',
    appId: '1:282053984724:ios:6d03885571fc4f98e99641',
    messagingSenderId: '282053984724',
    projectId: 'wa-apps-28f9a',
    storageBucket: 'wa-apps-28f9a.appspot.com',
    iosClientId: '282053984724-jnuvqjps172fsunvg35gfboagen5kvsq.apps.googleusercontent.com',
    iosBundleId: 'com.spyhunteritsolution.demoretail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJicLaUThPDnR0Kesa4W6_4TUw4Eqj1Ts',
    appId: '1:282053984724:ios:59cbd37b2868e73be99641',
    messagingSenderId: '282053984724',
    projectId: 'wa-apps-28f9a',
    storageBucket: 'wa-apps-28f9a.appspot.com',
    iosClientId: '282053984724-ehpi271tqktlgl79i319sg8oolf7gmnn.apps.googleusercontent.com',
    iosBundleId: 'com.newpackagename',
  );
}
